# Generated by Django 5.1.4 on 2025-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0006_subtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='color',
            field=models.CharField(default='#F5F6F7', max_length=100),
            preserve_default=False,
        ),
    ]
