# Generated by Django 5.1.4 on 2025-01-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0007_contacts_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskCategory',
            field=models.CharField(default='done', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone',
            field=models.CharField(blank=True, default=True, max_length=20),
        ),
    ]
