# Generated by Django 5.1.4 on 2025-01-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0010_remove_subtask_task_alter_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='user_auth_app.task'),
            preserve_default=False,
        ),
    ]
