# Generated by Django 5.1.4 on 2025-01-16 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0011_subtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='task',
        ),
    ]
