name: 🚀 Deploy website on push
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/schmidalbin15/projects/Join-Backend
          sudo git pull
          sudo ./env/bin/pip install -r requirements.txt